name: "CICD"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  molecule:
    name: "Test role with molecule"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run molecule
        uses: robertdebock/molecule-action@4.0.8
        env:
          ANSIBLE_FORCE_COLOR: '1'

  commitizen:
    needs: ["molecule"]
    name: "Bump version and create changelog with commitizen"
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  deploy:
    name: "Deploy role to Ansible Galaxy"
    needs: ["molecule", "commitizen"]
    runs-on: "ubuntu-latest"
    if: "github.event_name == 'push' && github.ref == 'main'"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: publish to galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_TOKEN }}
